
package itmo.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CameraService", targetNamespace = "http://webservices.itmo/", wsdlLocation = "http://localhost:8080/CameraService?wsdl")
public class CameraService
    extends Service
{

    private final static URL CAMERASERVICE_WSDL_LOCATION;
    private final static WebServiceException CAMERASERVICE_EXCEPTION;
    private final static QName CAMERASERVICE_QNAME = new QName("http://webservices.itmo/", "CameraService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CameraService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAMERASERVICE_WSDL_LOCATION = url;
        CAMERASERVICE_EXCEPTION = e;
    }

    public CameraService() {
        super(__getWsdlLocation(), CAMERASERVICE_QNAME);
    }

    public CameraService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAMERASERVICE_QNAME, features);
    }

    public CameraService(URL wsdlLocation) {
        super(wsdlLocation, CAMERASERVICE_QNAME);
    }

    public CameraService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAMERASERVICE_QNAME, features);
    }

    public CameraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CameraService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CameraWebService
     */
    @WebEndpoint(name = "CameraWebServicePort")
    public CameraWebService getCameraWebServicePort() {
        return super.getPort(new QName("http://webservices.itmo/", "CameraWebServicePort"), CameraWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CameraWebService
     */
    @WebEndpoint(name = "CameraWebServicePort")
    public CameraWebService getCameraWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.itmo/", "CameraWebServicePort"), CameraWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAMERASERVICE_EXCEPTION!= null) {
            throw CAMERASERVICE_EXCEPTION;
        }
        return CAMERASERVICE_WSDL_LOCATION;
    }

}
